# This file was generated by GoReleaser. DO NOT EDIT.
class DatadogTerraformer < Formula
  desc "Command Line Tool for exporting existing Datadog resources to HCL"
  homepage "https://github.com/kterada0509/datadog-terraformer"
  url "https://github.com/kterada0509/datadog-terraformer/releases/download/v0.0.6/datadog-terraformer_0.0.6_darwin_amd64.tar.gz"
  version "0.0.6"
  sha256 "a4797757f5a659b9a1e95032fdaba47234679f4785595e6dcb12e75ed316da62"

  def install
    bin.install "datadog-terraformer"
  end

  test do
    system "#{bin}/datadog-terraformer --version"
  end
end
